version: '3'
services:
  api:
    container_name: api
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/api
    command: npm run dev
    depends_on:
      - db
      - elasticsearch
    networks:
      - elastic
  db:
    image: percona:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api-template
    volumes:
    - ./data/mysql:/var/lib/mysql
    ports:
    - '13306:3306'
    networks:
      - elastic
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch
    ports:
    - '9200:9200'
    networks:
      - elastic
networks:
  elastic:
    driver: bridge